version: '3.1'

services:

  db:
    image: postgres:12
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: "habibi"
      POSTGRES_PASSWORD: "secret"
      POSTGRES_DB: "spring-k8s"