### Send POST request with json body
POST http://localhost:57397/api/persons
Content-Type: application/json

{
  "name": "John Doe",
  "email" : "john@doe2.fr"
}


### Get List of Persons

GET http://localhost:57397/api/persons
Accept: application/json