apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-k8s-demo
  labels:
    app: spring-k8s-demo
spec:
  replicas: 1
  template:
    metadata:
      name: spring-k8s-demo
      labels:
        app: spring-k8s-demo
    spec:
      containers:
        - name: spring-k8s-demo
          image: gildastema/spring-k8s-demo:0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: user
            - name: DB_PWD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: spring-k8s-config
                  key: db_port
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  key: db_host
                  name: spring-k8s-config

            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  key: db_name
                  name: spring-k8s-config

      restartPolicy: Always
  selector:
    matchLabels:
      app: spring-k8s-demo
