name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: habibi
          POSTGRES_DB: spring_k8s_db
          POSTGRES_PASSWORD: secret
          POSTGRES_PORT: 5432


    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Gradle
      run: chmod +x ./gradlew && ./gradlew build
      env:
        DB_USER: habibi
        DB_PWD: secret
        DB_NAME: spring_k8s_db
        DB_PORT: 5432
## Send to Docker
    - name: Set Up QMENU to connect to docker
      uses: docker/setup-qemu-action@v2
    - name: Set Up Docker Build Image
      uses: docker/setup-buildx-action@v2
    - name: Set Up Login To Docker
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and Push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: gildastema/spring-k8s-demo:latest,gildastema/spring-k8s-demo:0.1

